@startuml

!include https://raw.githubusercontent.com/Kyrales/1C-ER-plantuml/refs/heads/extended/main.puml

'header Техкружок 
title 1C Переводчики
caption Диаграмма объектов
'footer Команда ИТК, 2022

package НСИ <<folder>> {

    _Справочник(Произведения, "Произведения") {
        ТекстОригинал
        ТекстПеревод
    }
    _Справочник(Пользователи, "Пользователи")


    _РегистрСведений(ГрафикРаботы, "График работы") {
        <$d> Период
        <$r> РабочийДень
    }

}

package Планирование <<folder>> {

    _Документ(ПланПереводов, "План переводов") {
        -- Сотрудники --
        Пользователь
        Произведение
        План
    }
    
    _РегистрНакопления(ПланыПереводов, "Планы переводов") {
        <$d> ПериодПлана
        <$d> Пользователь
        <$d> Произведение
        <$r> План    
    }
}

package Перевод <<folder>> {
    
    _Документ(ДокПеревод, "Перевод") {
        Пользователь
        Произведение
        ТекстПеревода
        КоличествоСимволов
    }


}

Пользователи --- ПланПереводов::Пользователь
Произведения --- ПланПереводов::Произведение

Пользователи --- ДокПеревод::Пользователь
Произведения --- ДокПеревод::Произведение

Пользователи --- ПланыПереводов::Пользователь
Произведения --- ПланыПереводов::Произведение

ГрафикРаботы::Период --- ПланыПереводов::ПериодПлана

Перевод --> ПланыПереводов
ПланПереводов --> ПланыПереводов

@enduml