@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_WITH_LEGEND()

title Работа с переводами

' Системы
System_Boundary(ЛитУС, "1С: Литературные произведения") {
    Container(Лит_НСИ, "НСИ", "") {
        Component(ЛитПроизведения, "Справочник Произведения", , "")
    }
    Container(ЛитПереводы, "Переводы"){
        Component(ЛитПеревод, "Документ Перевод")
    }
}

System_Ext(ЛитФонд, "Литературный фонд")  

System_Boundary(УСПереводы, "1С: Переводчики") {
    Container(ЕРП_УчетНСИ, " НСИ") {
        Component(СправочникПроизведения,"Справочник Произведения")
    }
    Container(ПодсистемаПланирование, "Планирование"){
        Component(ПланПереводов, "Документ План переводов")
    }    
    Container(Переводы, "Переводы"){
        Component(ДокПеревод, "Документ Перевод")
    }
}

System_Ext(Кафка, "Kafka")

' Связи
Rel(ЛитФонд, СправочникПроизведения, "Произведения", "http")
Rel(СправочникПроизведения, Кафка, "Произведение", "TCP")
Rel(ДокПеревод, Кафка, "Перевод", "TCP")
Rel(Кафка, ЛитУС, "Готовый перевод", "TCP")

@enduml